# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_wordpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_word', models.CharField(max_length=255)),
                ('word_mean', models.CharField(max_length=255)),
            ],
        ),
    ]
